; This file was automatically generated by ScriptHubImporter.py
<<<<<<< HEAD
global g_ImportsGameVersion64 := 480
=======
global g_ImportsGameVersion64 := 500
>>>>>>> upstream/main
global g_ImportsGameVersionPostFix64 := ""