; This file was automatically generated by ScriptHubImporter.py
<<<<<<< Updated upstream
global g_ImportsGameVersion64 := 507
=======
global g_ImportsGameVersion64 := 501
>>>>>>> Stashed changes
global g_ImportsGameVersionPostFix64 := ""