; This file was automatically generated by ScriptHubImporter.py
<<<<<<< HEAD
global g_ImportsGameVersion64 := 512
=======
global g_ImportsGameVersion64 := 551
>>>>>>> upstream/main
global g_ImportsGameVersionPostFix64 := ""