;Automatic generated by Addon Management
#include *i %A_LineFile%\..\IC_About\IC_About_Component.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_Performance\IC_BrivGemFarm_Component.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_AdvancedSettings\IC_BrivGemFarm_AdvancedSettings_Includes.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_Potato\IC_BrivGemFarm_Component.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_Stats\IC_BrivGemFarm_Stats_Component.ahk
#include *i %A_LineFile%\..\IC_ChestPurchaser\IC_ChestPurchaser_Component.ahk
#include *i %A_LineFile%\..\IC_GameLocationSettings\IC_GameLocationSettings_Component.ahk
#include *i %A_LineFile%\..\IC_InventoryView\IC_InventoryView_Component.ahk
#include *i %A_LineFile%\..\IC_Jimothy\IC_Jimothy_Component.ahk
#include *i %A_LineFile%\..\IC_MemoryFunctions\IC_MemoryFunctions_Component.ahk
#include *i %A_LineFile%\..\IC_MemoryFunctionsFullRead\IC_MemoryFunctionsFullRead_Component.ahk
